site_name: Terraform Tutorial
docs_dir: chapters
plugins:
  - search
nav:
  - Home: index.md
  - Getting Started with Terraform:
    - Setting up the environment: "00-environment-setup.md"
    - Important Commands: "02-terraform-important-commands.md"
    - Terraform Providers: "03-providers.md"
    - Resources: "04-resources.md"
    - Resource Dependencies: "05-resource-dependencies.md"
    - Input and Output Variables: "06-variables-and-outputs.md"
    - Provisioners in detail: "07-provisioners.md"
    - Data Sources: "08-datasources.md"
    - State Management in Terraform: "09-terraform-state.md"
    - Backend and Statelocking: "10-backends.md"
    - Course Outline: "XX-course-outline.md"
theme: readthedocs
site_url: https://terraform-tutorial.schoolofdevops.com/
site_author: Gourav Shah
site_description: Terraform Tutorial by School of Devops
google_analytics: ['UA-36802546-19', 'terraform-tutorial.schoolofdevops.com']
repo_url: https://github.com/schoolofdevops/ultimate-terraform-bootcamp
edit_uri: edit/tree/chapters
copyright: Copyright @ 2017-2020 Gourav Shah, School of Devops. Some rights reserved. License CC BY-NC-SA
extra:
  social:
    - type: 'github'
      link: 'https://github.com/schoolofdevops'
    - type: 'twitter'
      link: 'https://twitter.com/gouravhah'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/gouravshah'
